# Generated by Django 5.2.3 on 2025-06-21 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptpayment',
            name='transaction_id',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
