# Generated by Django 5.2.3 on 2025-06-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_receiptpayment_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlinepayment',
            name='status',
        ),
        migrations.AddField(
            model_name='onlinepayment',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('fail', 'Fail'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
