# Generated by Django 5.2.3 on 2025-06-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_studentprofile_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='nic_no',
            field=models.CharField(unique=True),
        ),
    ]
