# Generated by Django 5.2.3 on 2025-06-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_studentprofile_nic_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='school_name',
            field=models.CharField(max_length=100),
        ),
    ]
