# Generated by Django 5.2.3 on 2025-06-25 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_alter_studentprofile_nic_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='year_of_al',
            field=models.IntegerField(),
        ),
    ]
