# Generated by Django 5.2.3 on 2025-06-26 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_alter_studentprofile_year_of_al'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
    ]
