# Generated by Django 5.2.3 on 2025-06-26 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_alter_studentprofile_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='courseid',
            new_name='classid',
        ),
    ]
