# Generated by Django 5.2.3 on 2025-06-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_rename_courseid_enrollment_classid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptpayment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
