# Generated by Django 5.2.3 on 2025-06-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_alter_receiptpayment_transaction_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receiptpayment',
            old_name='transaction_id',
            new_name='record_no',
        ),
        migrations.AddField(
            model_name='receiptpayment',
            name='account_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='receiptpayment',
            name='account_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='receiptpayment',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='receiptpayment',
            name='paid_amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='receiptpayment',
            name='paid_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
