# Generated by Django 5.2.1 on 2025-06-28 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_alter_receiptpayment_transaction_id'),
        ('students', '0019_paymenttest'),
    ]

    operations = [
    ]
