# Generated by Django 5.2.1 on 2025-06-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_remove_receiptpayment_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptpayment',
            name='record_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
