# Generated by Django 5.2.1 on 2025-06-28 18:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_merge_20250628_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiptpayment',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='onlinepayment',
            name='course_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='onlinepayment',
            name='course_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onlinepayment',
            name='initiated_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receiptpayment',
            name='account_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='receiptpayment',
            name='account_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='receiptpayment',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='receiptpayment',
            name='paid_amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='receiptpayment',
            name='paid_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receiptpayment',
            name='record_no',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
