# Generated by Django 5.2.3 on 2025-07-06 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0005_merge_20250629_1626'),
        ('students', '0021_studentprofile_profile_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=20, choices=[('exam', 'Exam'), ('webinar', 'Webinar'), ('custom', 'Custom')], default='custom')),
                ('date', models.DateTimeField()),
                ('color', models.CharField(max_length=20, default='gray')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_webinar', models.ForeignKey(null=True, blank=True, on_delete=models.SET_NULL, related_name='calendar_events', to='edu_admin.zoomwebinar')),
                ('related_exam', models.ForeignKey(null=True, blank=True, on_delete=models.SET_NULL, related_name='calendar_events', to='instructor.exams')),
            ],
        ),
    ]

