# Generated by Django 5.2.1 on 2025-06-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_remove_receiptpayment_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinepayment',
            name='course_ids',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
