# Generated by Django 5.2.1 on 2025-06-28 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0022_alter_onlinepayment_course_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlinepayment',
            name='course_summary',
        ),
    ]
