# Generated by Django 5.2.3 on 2025-07-18 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0023_chatroom_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onlinepayment',
            old_name='course_ids',
            new_name='class_ids',
        ),
        migrations.RenameField(
            model_name='onlinepayment',
            old_name='course_summary',
            new_name='class_summary',
        ),
    ]
