# Generated by Django 5.2.1 on 2025-06-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0023_remove_onlinepayment_course_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinepayment',
            name='course_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
