# Generated by Django 5.2.1 on 2025-06-28 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0024_onlinepayment_course_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlinepayment',
            name='initiated_at',
        ),
    ]
