# Generated by Django 5.2.3 on 2025-07-22 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_admin', '0004_zoomwebinar_registration_url'),
        ('instructor', '0006_remove_class_days_of_week_and_more'),
        ('students', '0024_rename_course_ids_onlinepayment_class_ids_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevent',
            name='classid',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='description',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='time',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='color',
            field=models.CharField(default='gray', max_length=20),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='related_exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='instructor.exams'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='related_webinar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='edu_admin.zoomwebinar'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='type',
            field=models.CharField(choices=[('exam', 'Exam'), ('webinar', 'Webinar'), ('custom', 'Custom')], default='custom', max_length=20),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
