# Generated by Django 5.2.3 on 2025-07-24 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0024_rename_course_ids_onlinepayment_class_ids_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat_room',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='paymenttest',
            name='user',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='PaymentTest',
        ),
    ]
