# Generated by Django 5.2.3 on 2025-07-24 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_admin', '0004_zoomwebinar_registration_url'),
        ('instructor', '0006_remove_class_days_of_week_and_more'),
        ('students', '0024_rename_course_ids_onlinepayment_class_ids_and_more'),
    ]

    operations = [
       
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('type', models.CharField(blank=True, choices=[('exam', 'Exam'), ('webinar', 'Webinar'), ('notes', 'Notes'), ('message', 'Message')], max_length=50, null=True)),
                ('read_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='students.studentprofile')),
            ],
        ),
    ]
