# Generated by Django 5.2.1 on 2025-06-28 18:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0025_remove_onlinepayment_initiated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinepayment',
            name='initiated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
