# Generated by Django 5.2.3 on 2025-06-29 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_studentprofile_city_studentprofile_district'),
        ('students', '0026_onlinepayment_initiated_at'),
    ]

    operations = [
    ]
