# Generated by Django 5.2.1 on 2025-08-24 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0025_chat_models'),
        ('students', '0028_remove_is_seen_column'),
    ]

    operations = [
    ]
