# Generated by Django 5.2.1 on 2025-08-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0029_merge_20250824_1421'),
    ]

    operations = [
        # This migration was created to add message status fields
        # but the fields were already added manually to the database
        # So this is a no-op migration to maintain migration consistency
    ]