# Generated by Django 5.2.1 on 2025-09-10 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0030_add_message_status_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        # PaymentTest table doesn't exist, so skip deletion
        migrations.RunSQL(
            "DROP TABLE IF EXISTS students_paymenttest CASCADE;",
            reverse_sql="",
        ),
    ]
