# Generated by Django 5.2.1 on 2025-09-18 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0031_alter_message_options_delete_paymenttest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentTest',
        ),
    ]
