# Generated by Django 5.2.3 on 2025-09-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0032_delete_paymenttest'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='class_names',
            field=models.TextField(blank=True, help_text='Comma-separated class names for this payment', null=True),
        ),
    ]
