# Generated by Django 5.2.3 on 2025-06-13 11:19

import django.db.models.deletion
import instructor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0001_initial'),
        ('students', '0005_enrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examid', models.CharField(max_length=20, unique=True)),
                ('examname', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('courseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.course')),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marksid', models.CharField(max_length=20, unique=True)),
                ('examid', models.CharField(max_length=100, verbose_name=instructor.models.Exams)),
                ('marks', models.FloatField()),
                ('stuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentprofile')),
            ],
        ),
    ]
