# Generated by Django 5.2.3 on 2025-06-26 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0002_exams_marks'),
        ('students', '0018_rename_courseid_enrollment_classid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Class',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='courseid',
            new_name='classid',
        ),
        migrations.RenameField(
            model_name='exams',
            old_name='courseid',
            new_name='classid',
        ),
        migrations.AlterField(
            model_name='marks',
            name='examid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.exams'),
        ),
    ]
