# Generated by Django 5.2.3 on 2025-06-26 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0002_exams_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='examid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.exams'),
        ),
    ]
