# Generated by Django 5.2.3 on 2025-06-28 14:41

import instructor.models
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0003_rename_course_class_rename_courseid_class_classid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='days_of_week',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=56, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=90),
        ),
        migrations.AddField(
            model_name='class',
            name='end_date',
            field=models.DateField(default=instructor.models.last_day_of_current_month),
        ),
        migrations.AddField(
            model_name='class',
            name='repeat',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='class',
            name='start_date',
            field=models.DateField(default=instructor.models.first_day_of_current_month),
        ),
        migrations.AddField(
            model_name='class',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
