# Generated by Django 5.2.3 on 2025-06-26 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0003_alter_marks_examid'),
        ('instructor', '0003_rename_course_class_rename_courseid_class_classid_and_more'),
    ]

    operations = [
    ]
