# Generated by Django 5.2.3 on 2025-06-29 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0004_class_days_of_week_class_duration_minutes_and_more'),
        ('instructor', '0004_merge_20250626_1811'),
    ]

    operations = [
    ]
