# Generated by Django 5.2.1 on 2025-07-07 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_admin', '0004_zoomwebinar_registration_url'),
        ('instructor', '0005_merge_20250629_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='days_of_week',
        ),
        migrations.RemoveField(
            model_name='class',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='class',
            name='start_time',
        ),
        migrations.AddField(
            model_name='class',
            name='webinar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='edu_admin.zoomwebinar'),
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=9)),
                ('start_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=90)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='instructor.class')),
            ],
        ),
    ]
