# Generated by Django 5.2.3 on 2025-07-04 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0005_instructorprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructorprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='instructorprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='instructorprofile',
            name='last_name',
        ),
    ]
