# Generated by Django 5.2.3 on 2025-07-25 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0006_remove_class_days_of_week_and_more'),
        ('instructor', '0006_remove_instructorprofile_email_and_more'),
    ]

    operations = [
    ]
