# Generated by Django 5.2.1 on 2025-08-05 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0006_remove_class_days_of_week_and_more'),
        ('instructor', '0007_merge_20250725_1443'),
    ]

    operations = [
    ]
