# Generated by Django 5.2.3 on 2025-07-25 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_admin', '0004_zoomwebinar_registration_url'),
        ('instructor', '0007_merge_20250725_1443'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('batch', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='study_notes')),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('related_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='edu_admin.zoomwebinar')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
