# Generated by Django 5.2.3 on 2025-07-24 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0006_remove_class_days_of_week_and_more'),
        ('instructor', '0007_studynote'),
    ]

    operations = [
    ]
