# Generated by Django 5.2.1 on 2025-08-24 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0008_merge_20250805_0915'),
        ('instructor', '0009_studynote'),
    ]

    operations = [
    ]
