# Generated by Django 5.2.3 on 2025-09-26 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0011_exam_examquestion_examsubmission_questionoption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studynote',
            name='related_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='instructor.class'),
        ),
    ]
