# Generated by Django 5.2.3 on 2025-09-27 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0012_alter_studynote_related_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studynote',
            name='batch',
        ),
    ]
