# Generated by Django 5.2.1 on 2025-06-22 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZoomWebinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webinar_id', models.CharField(max_length=50, unique=True)),
                ('account_key', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=255)),
                ('registration_url', models.URLField()),
                ('start_time', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('agenda', models.TextField(blank=True, null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZoomOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrence_id', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='edu_admin.zoomwebinar')),
            ],
            options={
                'unique_together': {('webinar', 'occurrence_id')},
            },
        ),
    ]
