# Generated by Django 5.2.1 on 2025-06-22 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu_admin', '0002_alter_zoomwebinar_registration_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zoomwebinar',
            name='registration_url',
        ),
    ]
