# Generated by Django 5.2.1 on 2025-06-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_admin', '0003_remove_zoomwebinar_registration_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoomwebinar',
            name='registration_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
