# Generated by Django 5.2.3 on 2025-06-13 07:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_course_paymentreceipt_onlinepayment_receiptpayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentReceipt',
            new_name='Payment',
        ),
    ]
