# Generated by Django 5.2.3 on 2025-06-13 08:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0001_initial'),
        ('students', '0004_delete_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('enrollid', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('courseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.course')),
                ('payid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.payment')),
                ('stuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentprofile')),
            ],
        ),
    ]
