# Generated by Django 5.2.3 on 2025-06-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_studentprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='mobile',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='nic_no',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='school_name',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='year_of_al',
            field=models.IntegerField(max_length=10),
        ),
    ]
