# Generated by Django 5.2.3 on 2025-06-25 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_alter_studentprofile_school_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='nic_no',
            field=models.IntegerField(unique=True),
        ),
    ]
