# Generated by Django 5.2.3 on 2025-06-25 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_alter_studentprofile_year_of_al'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='nic_no',
            field=models.CharField(unique=True),
        ),
    ]
