# Generated by Django 5.2.3 on 2025-06-25 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_alter_studentprofile_nic_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='nic_no',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
