# Generated by Django 5.2.3 on 2025-07-25 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0025_chatroom_message_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentTest',
        ),
    ]
