# Generated by Django 5.2.1 on 2025-08-05 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0025_chat_models'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='read_status',
            new_name='is_deleted',
        ),

    ]
